"""
-------------------------------------
# -*- coding: utf-8 -*-
# @Author  : nomalocaris
             Giyn
# @File    : main.py
# @Software: PyCharm
-------------------------------------
"""

from joblib import Parallel, delayed

from config import *
from dp_star import generate_adaptive_grid
from dp_star import generate_sd_grid_mapping_traj
from dp_star import mobility_model_main
from dp_star import route_length_estimate_main
from dp_star import synthetic_trajs
from dp_star import trip_distribution_main


import argparse
import pickle
from fractions import Fraction
from pathlib import Path


mdl_trajs_path = 'data/{}/MDL/'
top_grid_path = 'data/{}/Middleware/top_grid_epsilon_{}.txt'
grid_trajs_path = 'data/{}/Middleware/grid_trajs_epsilon_{}.txt'
grid_block_gps_range_path = 'data/{}/Middleware/grid_block_gps_range_epsilon_{}.txt'
trip_distribution_path = 'data/{}/Middleware/trip_distribution_epsilon_{}.txt'
midpoint_movement_path = 'data/{}/Middleware/midpoint_movement_epsilon_{}.txt'
length_traj_path = 'data/{}/Middleware/routes_length_epsilon_{}.txt'
sd_path = 'data/{}/SD/sd_epsilon_{}.txt'
sd_final_path = 'data/{}/SD/sd_final_epsilon_{}'

BASE_DIR = Path(__file__).resolve().parent


def parse_float_or_fraction(value: str) -> float:
    value = value.strip()

    if "/" in value:
        return float(Fraction(value))

    return float(value)


def parse_epsilon_list(value: str):
    """
    Example:
        "0.1,0.5,1.0,2.0"
    """
    return [float(v.strip()) for v in value.split(",") if v.strip()]


def parse_epsilon_alloc(value: str):
    """
    Expected order:
        ag,td,markov,mle

    Example:
        "1/9,3/9,4/9,1/9"
        "0.111111,0.333333,0.444444,0.111111"
    """
    parts = [p.strip() for p in value.split(",") if p.strip()]

    if len(parts) != 4:
        raise ValueError(
            "--epsilon-alloc must contain 4 values: ag,td,markov,mle"
        )

    parsed = [parse_float_or_fraction(p) for p in parts]

    total = sum(parsed)
    if abs(total - 1.0) > 1e-6:
        raise ValueError(
            f"--epsilon-alloc must sum to 1.0, but got {total}"
        )

    return {
        "ag": parsed[0],
        "td": parsed[1],
        "markov": parsed[2],
        "mle": parsed[3],
    }


def count_prepared_trajectories():
    """
    Reads the prepared DP-Star trajectory-name pickle.

    This should normally match the number of trajectories generated by
    prepare_dpstar_dataset.py.
    """
    name_list_path = BASE_DIR / "data" / USE_DATA / "trajs_file_name_list.pkl"

    if not name_list_path.exists():
        return None

    with name_list_path.open("rb") as f:
        names = pickle.load(f)

    return len(names)


def parse_args():
    parser = argparse.ArgumentParser(
        description="Run DP-Star with command-line parameters."
    )

    parser.add_argument(
        "--epsilons",
        default=",".join(str(e) for e in epsilon_list),
        help="Comma-separated epsilon values, e.g. 0.1,0.5,1.0,2.0.",
    )

    parser.add_argument(
        "--n-top-grid",
        type=int,
        default=n_top_grid,
        help="Top-grid size for DP-Star adaptive grid. Default comes from config.py.",
    )

    parser.add_argument(
        "--beta-factor",
        type=float,
        default=beta_factor,
        help="DP-Star adaptive-grid beta factor. Smaller value creates more bottom grids.",
    )

    parser.add_argument(
        "--epsilon-alloc",
        default=",".join(str(epsilon_alloc[k]) for k in ["ag", "td", "markov", "mle"]),
        help="Budget allocation as ag,td,markov,mle. Example: 1/9,3/9,4/9,1/9.",
    )

    parser.add_argument(
        "--synthetic-count",
        type=int,
        default=None,
        help=(
            "Number of synthetic trajectories to generate. "
            "Default: number from trajs_file_name_list.pkl, then fallback to TRAJS_NUM[USE_DATA]."
        ),
    )

    parser.add_argument(
        "--mapping-rate",
        type=float,
        default=MDL_SCALING_RATE[USE_DATA],
        help=(
            "MDL scaling/mapping rate used to convert synthetic MDL coordinates back to GPS. "
            "Must match prepare_dpstar_dataset.py --scaling-rate."
        ),
    )

    return parser.parse_args()


# def run(epsilon):
#     if not os.path.exists(f'data/{USE_DATA}/Middleware'):
#         os.mkdir(f'data/{USE_DATA}/Middleware')
#
#     # generate adaptive grid
#     n_grid = generate_adaptive_grid(
#         mdl_trajs_dir=mdl_trajs_path.format(USE_DATA),
#         top_grid_path=top_grid_path.format(USE_DATA, epsilon),
#         grid_trajs_path=grid_trajs_path.format(USE_DATA, epsilon),
#         grid_block_gps_range_path=grid_block_gps_range_path.format(USE_DATA, epsilon),
#         n_top_grid=n_top_grid,
#         epsilon_alloc=epsilon_alloc['ag'] * epsilon,
#         epsilon_total=epsilon,
#         gps_range=gps_range,
#         beta_factor=beta_factor
#     )
#
#     trip_distribution_main(n_grid, _epsilon=epsilon_alloc['td'] * epsilon,
#                            grid_trajs_path=grid_trajs_path.format(USE_DATA, epsilon),
#                            trip_distribution_path=trip_distribution_path.format(USE_DATA, epsilon))
#
#     mobility_model_main(n_grid, _epsilon=epsilon_alloc['markov'] * epsilon,
#                         grid_trajs_path=grid_trajs_path.format(USE_DATA, epsilon),
#                         midpoint_movement_path=midpoint_movement_path.format(USE_DATA, epsilon))
#
#     maxT = route_length_estimate_main(n_grid, _epsilon=epsilon_alloc['mle'] * epsilon,
#                                       grid_trajs_path=grid_trajs_path.format(USE_DATA, epsilon),
#                                       routes_length_path=length_traj_path.format(USE_DATA, epsilon))
#
#     if not os.path.exists(f'data/{USE_DATA}/SD'):
#         os.mkdir(f'data/{USE_DATA}/SD')
#
#     synthetic_trajs(n_grid, maxT, trip_distribution_path.format(USE_DATA, epsilon),
#                     midpoint_movement_path.format(USE_DATA, epsilon), length_traj_path.format(USE_DATA, epsilon),
#                     sd_path.format(USE_DATA, epsilon), TRAJS_NUM[USE_DATA])
#
#     # generate sd trajectory
#     generate_sd_grid_mapping_traj(
#         sd_path=sd_path.format(USE_DATA, epsilon),
#         grid_block_gps_range_path=grid_block_gps_range_path.format(USE_DATA, epsilon),
#         sd_final_path=sd_final_path.format(USE_DATA, epsilon),
#         mapping_rate=MDL_SCALING_RATE[USE_DATA],
#         mapping_bias=mapping_bias
#     )

def run(epsilon, run_config):
    middleware_dir = BASE_DIR / "data" / USE_DATA / "Middleware"
    sd_dir = BASE_DIR / "data" / USE_DATA / "SD"

    middleware_dir.mkdir(parents=True, exist_ok=True)
    sd_dir.mkdir(parents=True, exist_ok=True)

    alloc = run_config["epsilon_alloc"]

    # generate adaptive grid
    n_grid = generate_adaptive_grid(
        mdl_trajs_dir=mdl_trajs_path.format(USE_DATA),
        top_grid_path=top_grid_path.format(USE_DATA, epsilon),
        grid_trajs_path=grid_trajs_path.format(USE_DATA, epsilon),
        grid_block_gps_range_path=grid_block_gps_range_path.format(USE_DATA, epsilon),
        n_top_grid=run_config["n_top_grid"],
        epsilon_alloc=alloc["ag"] * epsilon,
        epsilon_total=epsilon,
        gps_range=gps_range,
        beta_factor=run_config["beta_factor"],
    )

    trip_distribution_main(
        n_grid,
        _epsilon=alloc["td"] * epsilon,
        grid_trajs_path=grid_trajs_path.format(USE_DATA, epsilon),
        trip_distribution_path=trip_distribution_path.format(USE_DATA, epsilon),
    )

    mobility_model_main(
        n_grid,
        _epsilon=alloc["markov"] * epsilon,
        grid_trajs_path=grid_trajs_path.format(USE_DATA, epsilon),
        midpoint_movement_path=midpoint_movement_path.format(USE_DATA, epsilon),
    )

    maxT = route_length_estimate_main(
        n_grid,
        _epsilon=alloc["mle"] * epsilon,
        grid_trajs_path=grid_trajs_path.format(USE_DATA, epsilon),
        routes_length_path=length_traj_path.format(USE_DATA, epsilon),
    )

    synthetic_trajs(
        n_grid,
        maxT,
        trip_distribution_path.format(USE_DATA, epsilon),
        midpoint_movement_path.format(USE_DATA, epsilon),
        length_traj_path.format(USE_DATA, epsilon),
        sd_path.format(USE_DATA, epsilon),
        run_config["synthetic_count"],
    )

    generate_sd_grid_mapping_traj(
        sd_path=sd_path.format(USE_DATA, epsilon),
        grid_block_gps_range_path=grid_block_gps_range_path.format(USE_DATA, epsilon),
        sd_final_path=sd_final_path.format(USE_DATA, epsilon),
        mapping_rate=run_config["mapping_rate"],
        mapping_bias=mapping_bias,
    )


# if __name__ == '__main__':
#     Parallel(n_jobs=4)(delayed(run)(i) for i in epsilon_list)

if __name__ == "__main__":
    args = parse_args()

    epsilons = parse_epsilon_list(args.epsilons)
    parsed_epsilon_alloc = parse_epsilon_alloc(args.epsilon_alloc)
    n_jobs = min(4, len(epsilons))

    prepared_count = count_prepared_trajectories()

    if args.synthetic_count is not None:
        synthetic_count = args.synthetic_count
    elif prepared_count is not None:
        synthetic_count = prepared_count
    else:
        synthetic_count = TRAJS_NUM[USE_DATA]

    run_config = {
        "n_top_grid": args.n_top_grid,
        "beta_factor": args.beta_factor,
        "epsilon_alloc": parsed_epsilon_alloc,
        "synthetic_count": synthetic_count,
        "mapping_rate": args.mapping_rate,
    }

    print("DP-Star parameters:")
    print(f"USE_DATA = {USE_DATA}")
    print(f"epsilons = {epsilons}")
    print(f"n_jobs = {n_jobs}")
    print(f"n_top_grid = {run_config['n_top_grid']}")
    print(f"beta_factor = {run_config['beta_factor']}")
    print(f"epsilon_alloc = {run_config['epsilon_alloc']}")
    print(f"synthetic_count = {run_config['synthetic_count']}")
    print(f"mapping_rate = {run_config['mapping_rate']}")
    print(f"gps_range = {gps_range}")
    print(f"mapping_bias = {mapping_bias}")

    Parallel(n_jobs=n_jobs)(
        delayed(run)(epsilon, run_config)
        for epsilon in epsilons
    )
